In [1]:
!pip install simpledbf

Collecting simpledbf
  Downloading https://files.pythonhosted.org/packages/8a/d3/e4c25cd8f739dd7ddd19c255cd5552e08cdd439ac51a36ae12640ce8a748/simpledbf-0.2.6.tar.gz
Building wheels for collected packages: simpledbf
  Building wheel for simpledbf (setup.py) ... done
  Created wheel for simpledbf: filename=simpledbf-0.2.6-cp37-none-any.whl size=13793 sha256=4663838b2482366fb01fbfa609320075e1357731f45d489debbd66111654f4f9
  Stored in directory: /root/.cache/pip/wheels/72/dd/df/cdfb970a508ef9750ebb4b6e035a3410c3d62b5a6a91d2aafc
Successfully built simpledbf
Installing collected packages: simpledbf
Successfully installed simpledbf-0.2.6

In [2]:
import shutil
import urllib.request as request
from contextlib import closing
import zipfile
import shutil
import sys
import os
from pathlib import Path
import pandas as pd
from simpledbf import Dbf5
import platform

#define a função de download
def download_ftp(url, savepath):
    with closing(request.urlopen(url)) as r:
        with open(savepath, 'wb') as f:
            shutil.copyfileobj(r, f)

root = Path(".")

In [3]:
#Paulo criou a pasta aqui? 
dbf_save_folder = root / "SINASC_DBF"
csv_save_folder = root / "SINASC_CSV"

dbf_save_folder.mkdir(exist_ok=True)
csv_save_folder.mkdir(exist_ok=True)

In [4]:
SINASC_URL = "http://svs.aids.gov.br/dantps/centrais-de-conteudos/dados-abertos/sinasc/DNBR20DA.zip"

In [6]:
print("Downloading", SINASC_URL.split("/")[-1])
save_path = dbf_save_folder / SINASC_URL.split("/")[-1]
download_ftp(SINASC_URL, save_path)

Downloading DNBR20DA.zip

In [7]:
with zipfile.ZipFile(save_path, 'r') as zip_ref:
    zip_ref.extractall(dbf_save_folder)

In [8]:
!ls SINASC_DBF/

DNBR20DA.DBF  DNBR20DA.zip

In [9]:
filepath = (dbf_save_folder/'DNBR20DA.DBF') #('C:/Users/spereira/OneDrive - Padtec/Documents/Unicamp/Projeto/DNBR20DA.DBF')
dbf = Dbf5(filepath)
dbf.to_csv(csv_save_folder/'DNBR20DA.csv')

In [10]:
!ls SINASC_CSV/

DNBR20DA.csv

In [12]:
filepath = Path(csv_save_folder/'DNBR20DA.csv')
df = pd.read_csv(filepath)
df

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (34) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

               CODINST  ORIGEM   CODESTAB  ...  TPROBSON  PARIDADE  KOTELCHUCK
0        MPR4113700001       1  7758391.0  ...         5         1           5
1        MPR4113700001       1  7758391.0  ...         5         1           5
2        MPR4113700001       1  7758391.0  ...         4         1           5
3        MPR4113700001       1  2579391.0  ...         2         0           5
4        MPR4113700001       1  2579391.0  ...         5         1           5
...                ...     ...        ...  ...       ...       ...         ...
2687646  EDF5300100002       1  3018520.0  ...         3         1           4
2687647  EDF5300100002       1  3018520.0  ...         5         1           4
2687648  EDF5300100002       1  3018520.0  ...         1         0           5
2687649  EDF5300100002       1  5717515.0  ...         3         1           5
2687650  EDF5300100002       1    10545.0  ...         1         0           2

[2687651 rows x 62 columns]

In [13]:

cols = ["DTNASC", "QTDFILVIVO", "SEXO", "IDADEMAE", "PESO", "GRAVIDEZ", "CONSULTAS", "RACACOR", "CODMUNNASC", "ESTCIVMAE", "ESCMAE", "PARTO", "IDANOMAL"]
df = pd.read_csv(filepath, usecols=cols)

In [14]:
df

         CODMUNNASC  IDADEMAE  ESTCIVMAE  ...  RACACOR    PESO  IDANOMAL
0            411370      35.0        2.0  ...      4.0  3000.0       2.0
1            411370      33.0        2.0  ...      1.0  3340.0       2.0
2            411370      35.0        4.0  ...      1.0  3470.0       2.0
3            411370      17.0        5.0  ...      1.0  2660.0       2.0
4            411370      23.0        5.0  ...      1.0  3610.0       2.0
...             ...       ...        ...  ...      ...     ...       ...
2687646      530010      32.0        2.0  ...      4.0  2915.0       2.0
2687647      530010      31.0        2.0  ...      4.0  2955.0       2.0
2687648      530010      34.0        2.0  ...      4.0  3230.0       2.0
2687649      530010      24.0        9.0  ...      4.0  3285.0       2.0
2687650      530010      17.0        1.0  ...      NaN  3175.0       2.0

[2687651 rows x 13 columns]